Iesniedzu otro majasdarbu
DeKristaps/home-exercises-05-2022 pull request #4
Opened 2022-09-13 15:24 UTC by DeKristaps

2022-09-23 18:47 UTC, NilsKula requested changes
:+1:

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/flowcontrol/practice/LargestNumber.java
> +            if (num1 > num3) {
šo varētu pirmajam if pielikt klāt `&&`

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/flowcontrol/practice/LargestNumber.java
> +            if (num2 > num3) {
`} else if() {`

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/flowcontrol/practice/LargestNumber.java
> +                System.out.println("The largest number is " + num3);
un tad bez ši duplikāta varētu iztikt, ka paliek tik beigās

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/flowcontrol/practice/PhoneKeyPad.java
> +            if ((test == 'a') || (test == 'b') || (test == 'c')) {
viss pareizi, šeit tik ar `case` sanāktu noteikti īsāk/smukāk

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/flowcontrol/practice/PrintDayInWord.java
> +    public static String switchStatement(int num) {
the better choice :smile:

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/flowcontrol/practice/TenBillion.java
> +                } else if ((n >= 100) && (n < 1000)) {
kad tiek līdz šejienei, tad jau ir pārbaudīts, ka nav mazāks par 100 :thinking:

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/flowcontrol/practice/TenBillion.java
> +                } else if ((n >= 1000000000) && (n < 10000000000L)) {
pēdejam ar `else` šķiet ka varētu pietikt?
un tās iekavas ap katru nav vajadzīgas šajā gadijumā

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/loops/practice/Exercise5.java
> +        for (int i = 0; i < 30 - dodLength; i++) {
30 varētu izvilkt kā konstanti

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/loops/practice/MultiplyByItself.java
> +
:thinking:

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/loops/practice/Piglet.java
> +            userChoice = userInput.next();
laba vieta, lai izmantotu `.toLowerCase()`

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/loops/practice/RollTwoDice.java
> +        int d1, d2, diceSum;
labāk katru jaunā rindā

2022-09-23 18:47 UTC, NilsKula commented on Homework/src/main/java/io/codelex/loops/practice/RollTwoDice.java
> +            d1 = dice.nextInt(1, 7);
tā kā atkartojas, laba iespēja izvilkt uz palīgmetodi, piemēram `.rollDice()`

2022-09-23 20:25 UTC, DeKristaps commented on Homework/src/main/java/io/codelex/loops/practice/MultiplyByItself.java
> +
Atvainojos. izskatās ka nejauši pārlecu šim pāri. Tagad ir iesniegts.

2022-09-30 15:54 UTC, NilsKula approved these changes

2022-09-30 17:29 UTC, merged